// Writes dist/sw.js after `vite build`: a service worker that precaches every
// file of the build, so the home-screen app opens without a network.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const dist = 'dist';
const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (name !== 'sw.js') files.push(relative(dist, p).replaceAll(sep, '/'));
  }
})(dist);

const hash = createHash('sha1');
for (const f of files) hash.update(f).update(readFileSync(join(dist, f)));
const version = hash.digest('hex').slice(0, 12);
const urls = ['./', ...files.filter((f) => f !== 'index.html').map((f) => './' + f)];

const sw = `// Generated by scripts/pwa.mjs. Version ${version}.
const CACHE = 'water-sort-${version}';
const URLS = ${JSON.stringify(urls)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(URLS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});

// Cache first for everything in the build; the page itself is refreshed in the background
// so a new deploy shows up on the next launch.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true, ignoreVary: true }).then((hit) => {
      const fresh = fetch(req)
        .then((res) => {
          if (res.ok) caches.open(CACHE).then((c) => c.put(req, res.clone()));
          return res;
        })
        .catch(() => hit);
      if (!hit) return fresh;
      // Navigations start the refresh (fresh is already in flight) but answer from the cache at once.
      if (req.mode === 'navigate') e.waitUntil(fresh.then(() => undefined, () => undefined));
      return hit;
    }),
  );
});
`;
writeFileSync(join(dist, 'sw.js'), sw);
console.log('wrote dist/sw.js:', urls.length, 'files precached, version', version);
